### ISSUE TITLE
实验3过程中遇到的一些问题

### ISSUE THREAD

**Issue by WenzeJin** [CYL-collab/softwareTestingEx#3]
使用 Safari 浏览器时，默认的测试代码下（仓库里的测试代码），总是会遇到一些无法找到某些按钮的问题，比如`reset-app-state`这个链接。并且发现同样的测试用例（比如测试不同商品加入购物车时），总是前面几个出现无法找到按钮，但后面就正常了，猜测是加载完毕的页面缓存了。所以，我在所有的新页面加载完成之后都加入了`time.sleep(1)`等待，包括但不限于`reset_app`等函数，最终得到了合理的测试结果。不知道这是为什么? 只使用`implicitly_wait`好像不太足够。

**Comment by WenzeJin** [comment]
同时
```python
    def test_checkout_and_payment(self):
        """测试填写收货信息和确认订单的结算功能"""
        self.login("standard_user", "secret_sauce")
        self.reset_state()
        self.add_to_cart("add-to-cart-sauce-labs-backpack")
        self.driver.get("https://www.saucedemo.com/cart.html")
        time.sleep(1)
        self.driver.find_element(By.ID, 'checkout').click()
        # 填写收货信息
        self.driver.find_element(By.ID, 'first-name').send_keys("123 Main St")
        self.driver.find_element(By.ID, 'last-name').send_keys("12345")
        self.driver.find_element(By.ID, 'postal-code').send_keys("12345")
        self.driver.find_element(By.ID, 'continue').click()
        # 确认订单
        finish_button = self.driver.find_element(By.ID, 'finish')
        finish_button.click()
        # 验证是否成功生成订单
        confirmation_message = self.driver.find_element(By.ID, 'checkout_complete_container').text
        self.assertIn(confirmation_message, "Thank you for your order!\nYour order has been dispatched, and will arrive just as fast as the pony can get there!\nBack Home")
```
这里的 提示信息 assert 与网站返回的不符，会报错，实测应当把`\n`去掉

**Comment by CYL-collab** [comment]
> 同时
> 
> ```python
>     def test_checkout_and_payment(self):
>         """测试填写收货信息和确认订单的结算功能"""
>         self.login("standard_user", "secret_sauce")
>         self.reset_state()
>         self.add_to_cart("add-to-cart-sauce-labs-backpack")
>         self.driver.get("https://www.saucedemo.com/cart.html")
>         time.sleep(1)
>         self.driver.find_element(By.ID, 'checkout').click()
>         # 填写收货信息
>         self.driver.find_element(By.ID, 'first-name').send_keys("123 Main St")
>         self.driver.find_element(By.ID, 'last-name').send_keys("12345")
>         self.driver.find_element(By.ID, 'postal-code').send_keys("12345")
>         self.driver.find_element(By.ID, 'continue').click()
>         # 确认订单
>         finish_button = self.driver.find_element(By.ID, 'finish')
>         finish_button.click()
>         # 验证是否成功生成订单
>         confirmation_message = self.driver.find_element(By.ID, 'checkout_complete_container').text
>         self.assertIn(confirmation_message, "Thank you for your order!\nYour order has been dispatched, and will arrive just as fast as the pony can get there!\nBack Home")
> ```
> 
> 这里的 提示信息 assert 与网站返回的不符，会报错，实测应当把 `\n` 去掉

此处的断言在 Edge 131.0.2903.86 可以通过，可能是 Chromium 和 Webkit 在这边的处理策略不同

**Comment by CYL-collab** [comment]
> 使用 Safari 浏览器时，默认的测试代码下（仓库里的测试代码），总是会遇到一些无法找到某些按钮的问题，比如 `reset-app-state` 这个链接。并且发现同样的测试用例（比如测试不同商品加入购物车时），总是前面几个出现无法找到按钮，但后面就正常了，猜测是加载完毕的页面缓存了。所以，我在所有的新页面加载完成之后都加入了 `time.sleep(1)` 等待，包括但不限于 `reset_app` 等函数，最终得到了合理的测试结果。不知道这是为什么？只使用 `implicitly_wait` 好像不太足够。

找不到元素的原因大概率是 `implicitly_wait` 时间相应元素内没加载完成，建议增加 `implicitly_wait` 时间。这并不会太浪费测试时间，因为在设定的时间内一旦找到元素，代码就会立即继续执行。或者改用 Explicit waits 也是一种选项。
